# Build for Angular project

trigger:
  batch: true
  branches:
    include:
    - '*'
    exclude:
    - master # master excluded because it stores GitHub Pages files

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '10.x'

- task: Npm@1
  displayName: 'Install npm'
  inputs:
    command: 'install'

- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: 'custom'
    customCommand: 'run build'
