# Build for Angular project

trigger:
  batch: true
  branches:
    include:
    - '*'
    exclude:
    - master # master excluded because it stores GitHub Pages files

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'
