# Build for Angular project

trigger:
  batch: true
  branches:
    include:
    - '*'
    exclude:
    - master # master excluded because it stores GitHub Pages files

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build'
  jobs:
    - job: Build
      displayName: 'Build'
      steps:
      - task: NodeTool@0
        displayName: 'Install Node.js'
        inputs:
          versionSpec: '10.x'

      - task: Npm@1
        displayName: 'Install npm'
        inputs:
          command: 'install'

      - task: Npm@1
        displayName: 'npm run build'
        inputs:
          command: 'custom'
          customCommand: 'run build'

      - task: Npm@1
        displayName: 'npm run test'
        inputs:
          command: 'custom'
          customCommand: 'run test'

      - task: PublishCodeCoverageResults@1
        displayName: 'Publish code coverage results'
        condition: succeededOrFailed()
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: 'coverage/cobertura-coverage.xml'
          reportDirectory: coverage
          failIfCoverageEmpty: true

      - task: PublishTestResults@2
        displayName: 'Publish test results'
        condition: succeededOrFailed()
        inputs:
          searchFolder: $(System.DefaultWorkingDirectory)/junit
          testRunTitle: Angular
          testResultsFormat: JUnit
          testResultsFiles: "**/TESTS*.xml"

      - task: PublishPipelineArtifact@1
        displayName: 'Publish Pipeline Artifact: website'
        inputs:
          path: '$(System.DefaultWorkingDirectory)/dist'
          artifact: 'website'

- stage: GitHubPages
  displayName: 'GitHub Pages'
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/source'))
  jobs:
    - deployment: Publish
      displayName: 'Publish GitHub Pages'
      environment: 'GitHub Pages'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: CmdLine@2
              displayName: 'Publish GitHub Pages'
              inputs:
                script: 'ng deploy --branch=master'
